name: Deploy to Server

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          echo "UserKnownHostsFile /dev/null" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Deploy to Server 1
        run: |
          ssh -T -i ~/.ssh/deploy_key.pem \
            -o StrictHostKeyChecking=no \
            ${{ vars.EC2_USER }}@${{ secrets.EC2_HOST1 }} << 'EOF'
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/demo-appwithflask:latest
            sudo docker stop demo-appwithflask || true
            sudo docker rm demo-appwithflask || true
            sudo docker run --name demo-appwithflask -d -p 80:80 \
              ${{ secrets.DOCKER_USERNAME }}/demo-appwithflask:latest
          EOF

      - name: Health check Server 1
        run: |
          sleep 20
          HOST=$(echo "${{ secrets.EC2_HOST1 }}" | tr -d '[:space:]')
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://${HOST}/health)
          if [ "$STATUS" != "200" ]; then
            echo "Server 1 health check failed. Status: $STATUS"
            exit 1
          fi
          echo "Server 1 is running. Status: $STATUS"

      - name: Deploy to Server 2
        run: |
          ssh -T -i ~/.ssh/deploy_key.pem \
            -o StrictHostKeyChecking=no \
            ${{ vars.EC2_USER }}@${{ secrets.EC2_HOST2 }} << 'EOF'
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/demo-appwithflask:latest
            sudo docker stop demo-appwithflask || true
            sudo docker rm demo-appwithflask || true
            sudo docker run --name demo-appwithflask -d -p 80:80 \
              ${{ secrets.DOCKER_USERNAME }}/demo-appwithflask:latest
          EOF

      - name: Health check Server 2
        run: |
          sleep 20
          HOST=$(echo "${{ secrets.EC2_HOST1 }}" | tr -d '[:space:]')
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://${HOST}/health)
          if [ "$STATUS" != "200" ]; then
            echo "Server 2 health check failed. Status: $STATUS"
            exit 1
          fi
          echo "Server 2 is running. Status: $STATUS"
